### ISSUE TITLE
Mention extension API in docs

### ISSUE THREAD

**Issue by ChristianChiarulli** [LukasPietzschmann/telescope-tabs#1]
```
:lua require('telescope').extensions["telescope-tabs"].list_tabs(require('telescope.themes').get_dropdown{previewer = false, initial_mode='normal', prompt_title='Tabs'})
```

**Comment by LukasPietzschmann** [comment]
Do you think I should create a `doc/telescope-tabs.txt` file so that users could use neovims help system? Or is it enough to just expand the `README.md`?

**Comment by ChristianChiarulli** [comment]
For now I think the readme is enough, but adding more official docs can't hurt. I would also consider renaming the API so that you can access with "dot" notation

`telescope-tabs` -> `telescope_tabs`

This is kind of a nitpick feel free to ignore it.

**Comment by LukasPietzschmann** [comment]
> This is kind of a nitpick feel free to ignore it.

No worries, I am a big fan of those little nitpicky improvements.
I'll add additional documentation and change the name as soon as I've got time.

**Comment by LukasPietzschmann** [comment]
So I added a doc.txt file with more information. Do you think that this is sufficient?

I thought a bit about renaming the extension. If I did that, every one using it currently (which are probably not many people) would have to change their config to adapt to the new name. Also, I would need to rename the repo, which I'm not really a fan of. So I think I probably won't rename it.
