### ISSUE TITLE
Use `vim.notify` api call to report errors, instead of just `print`

### ISSUE THREAD

**Issue by vtselfa** [LukasPietzschmann/telescope-tabs#10]
By using [vim.notify](https://neovim.io/doc/user/lua.html#vim.notify()) the user can have a nicer experience, overriding the function with plugins like https://github.com/rcarriga/nvim-notify

An example where this could be applied is when reporting the error:
`print 'No previous tab to go to'`, in main.lua

**Comment by LukasPietzschmann** [comment]
Thanks for pointing me at `vim.notify`. I actually didn't know this existed.
I substituted both `print`s, but was not totally sure about what log-level to choose. I thought maybe `vim.log.levels.ERROR` is fine, as the desired action could not be executed. But maybe a warning would be more friendly? What's your opinion on this?
