### ISSUE TITLE
[Config Recipe] Support Tabby TabName

### ISSUE THREAD

**Issue by IceS2** [LukasPietzschmann/telescope-tabs#14]
Hello o/
I was fiddling around with Tabby and telescope-tabs to see if I could actually make it work with the names I setup for the tabs and I came out with this following config:

```lua
      require("telescope-tabs").setup {
        entry_formatter = function(tab_id, buffer_ids, file_names, file_paths, is_current)
            local tab_name = require("tabby.feature.tab_name").get(tab_id)
            return string.format("%d: %s%s", tab_id, tab_name, is_current and " <" or "")
        end,
        entry_ordinal = function(tab_id, buffer_ids, file_names, file_paths, is_current)
          return require("tabby.feature.tab_name").get(tab_id)
        end
      }
```

Just leaving it here in case you want to add it to the wiki (=

**Comment by LukasPietzschmann** [comment]
How cool is that! I use tabby myself, and I'll probably use this snippet in my own config :)
Thanks a lot for sharing, I'll definitely put it in the wiki.
