### ISSUE TITLE
It simply only shows the tab i am in, not the others that exists

### ISSUE THREAD

**Issue by hrqmonteiro** [LukasPietzschmann/telescope-tabs#22]
https://github.com/LukasPietzschmann/telescope-tabs/assets/17055027/68aa4394-5b37-460c-a601-b1a675105e47

**Comment by LukasPietzschmann** [comment]
Hi @hrqmonteiro!

Hm, my first guess would be, that you are not displaying tabs in your top bar, but open buffers. You could try opening new tabs with `:tabe <filename>`, and then checking telescope-tabs again (I provided a short video to make it clear what I mean 😄). Depending on the outcome, there are two possible solutions:
1. If telescope-tabs shows the files you opened with `:tabe`, you are indeed only displaying open bufferes. In this case, you can use `:Telescope buffers` to switch between them.
2. If telescope-tabs still only shows one tab, despite you using `:tabe`, this is an actual bug :) In this case, it would be helpful if you could provide your config.

[Demo.webm](https://github.com/LukasPietzschmann/telescope-tabs/assets/49213919/14720b77-7d54-4078-841b-5a9005821b0b)

**Comment by hrqmonteiro** [comment]
> Hi @hrqmonteiro!
> 
> Hm, my first guess would be, that you are not displaying tabs in your top bar, but open buffers. You could try opening new tabs with `:tabe <filename>`, and then checking telescope-tabs again (I provided a short video to make it clear what I mean 😄). Depending on the outcome, there are two possible solutions:
> 
>     1. If telescope-tabs shows the files you opened with `:tabe`, you are indeed only displaying open bufferes. In this case, you can use `:Telescope buffers` to switch between them.
> 
>     2. If telescope-tabs still only shows one tab, despite you using `:tabe`, this is an actual bug :) In this case, it would be helpful if you could provide your config.
> 
> 
> Screencast_20240516_080447.webm

Well in that way, it worked. With `tabe` it is fine.

But how can i make this work by default, then? If i may ask.

**Comment by LukasPietzschmann** [comment]
> But how can i make this work by default, then?

That's hard to answer, 'cause I don't really know what you are using, what your workflow is, our what you would be willing to change. But here are some possible ideas:
- If looks like you're using neo-tree to open files. You can configure neo-tree to open files in a new tab when you press enter. Or if you don't want to change the mappings, you can by default press t on a file to open it in a new tab (see [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/6e20108c4a8128782f534f5fe90c757b44212ef6/lua/neo-tree/defaults.lua#L380))
- You can also use telescope's file picker to open files in a new tab
- But be aware, that your bufferline at the top (I assume it's akinsho/bufferline.nvim) won't show tabs by default. But this can easily be changed (see [here](https://github.com/akinsho/bufferline.nvim?tab=readme-ov-file#tabpages))

I hope this helped a bit! If you still have questions, don't hesitate to ask :)
