### ISSUE TITLE
not able to preview no name tabs

### ISSUE THREAD

**Issue by yimingwangdell** [LukasPietzschmann/telescope-tabs#23]
not able to preview no name tabs

**Comment by LukasPietzschmann** [comment]
Thanks for pointing me to this issue!

At first glance, this looks more like an issue with telescope.nvim, since it also doesn't show content for unnamed files (and this plugin just uses telescope's default previewer). But I'll look more into it when I find some free time :)

**Comment by jamestrew** [comment]
I believe it's a telescope core issue as well.
See my comment here: https://github.com/nvim-telescope/telescope.nvim/issues/3221#issuecomment-2249115449

I have a PR open to address this for a while but I don't think other maintainers have had a chance to take a good look.

**Comment by LukasPietzschmann** [comment]
Thanks @jamestrew for pointing me to your pull request. Yesderday, I already searched telescope's repo for issues related to this, but somehow I didn't find [your PR](https://github.com/nvim-telescope/telescope.nvim/pull/2946) ':)

I'll close this issue then, as the encountered bug is not related to this repo.
