### ISSUE TITLE
Consider adding formatting config

### ISSUE THREAD

**Issue by ChristianChiarulli** [LukasPietzschmann/telescope-tabs#3]
`stylua` is a pretty widely accepted formatter across neovim plugins.

Consider adding a `.stylua.toml` file so that contributors can make contributions and keep consistent formatting.

Example: https://github.com/nvim-telescope/telescope.nvim/blob/master/.stylua.toml

**Comment by LukasPietzschmann** [comment]
Yeah, that's a great idea. I already use stylua for other projects, so I'll put my default config in this repo, too.

**Comment by LukasPietzschmann** [comment]
Fixed in [4d541d03c](https://github.com/LukasPietzschmann/telescope-tabs/commit/4d541d03c56f5c2c9723ec7a105f76a3c89326b3)
