### ISSUE TITLE
42c2fad41140256195d9eac27fc2cc9fd0976dbe

### ISSUE THREAD

**Issue by deborah1999** [LukasPietzschmann/telescope-tabs#4]

**Comment by LukasPietzschmann** [comment]
So I'm not completely sure what issue you are proposing here. I checked the commit [42c2fad41140256195d9eac27fc2cc9fd0976dbe](https://github.com/LukasPietzschmann/telescope-tabs/commit/42c2fad41140256195d9eac27fc2cc9fd0976dbe), but I didn't find any issue there.

**Comment by LukasPietzschmann** [comment]
So I'm going to close this for now. @deborah1999 if you wanna follow up on this issue, just comment here.
