### ISSUE TITLE
No action is taken after chaning entry_formatter

### ISSUE THREAD

**Issue by Drllap** [LukasPietzschmann/telescope-tabs#5]
Generally, I have many projects open, each in its own tab. I change the CWD in the tab to reflect the project it has open. 
So I changed the `entry_formatter` so that the CWD is shown in the telescope list:

```lua
require("telescope-tabs").setup{
  entry_formatter = function(tab_id, buffer_ids, file_names, file_paths)
    return vim.fn.getcwd(-1, tab_id)
  end
}
```

This works fine, as in the CWD is shown, but now no action is taken when an entry in the list is selected.
Can I configure the action?

**Comment by Drllap** [comment]
Doing it like this works:
```lua
local ef = function(tab_id, buffer_ids, file_names, file_paths)
  return vim.fn.getcwd(-1, tab_id)
end

vim.keymap.set('n', '<leader>tt', function() require('telescope-tabs').list_tabs({ entry_formatter = ef}) end)
```

**Comment by LukasPietzschmann** [comment]
Hmm that's kinda weird. I copied your configuration and I don't have any issues.
The only thing that's unexpected is that the picker always shows the same path. Do you have this issue too?

**Comment by Drllap** [comment]
> The only thing that's unexpected is that the picker always shows the same path. Do you have this issue too?

Did you remember to change the paths for the new tabs?

**Comment by LukasPietzschmann** [comment]
Oh yeah, I forgot this. I set the cwd using `tcd` but I still can't reproduce your bug.

I unfortunately cannot imagine why this would not work for you. If you look at [main.lua:119](https://github.com/LukasPietzschmann/telescope-tabs/blob/268ca2341c224e5d5f397bf72ce3623c8d9fcb8a/lua/telescope/_extensions/telescope-tabs/main.lua#L119)  we just use nvim's API to navigate to the given tab id (`value[5] := tab id` (see [main.lua:96](https://github.com/LukasPietzschmann/telescope-tabs/blob/268ca2341c224e5d5f397bf72ce3623c8d9fcb8a/lua/telescope/_extensions/telescope-tabs/main.lua#L96))). None of this behavior is influences by your custom `entry_formatter`.

What version of telescope and neovim are you using?

**Comment by Drllap** [comment]
Tested the original config again and you are right, the action indeed works.

What I think was the issue is the missing call to ``nvim_tabpage_get_number`` that I had already added in my second [version](https://github.com/LukasPietzschmann/telescope-tabs/issues/5#issuecomment-1329203538)

I'm guessing that the `tab_id` was just the currently selected `tabpage_number` when I was testing this so nothing happend

**Comment by LukasPietzschmann** [comment]
Alright, thanks for your feedback :)

**Comment by LukasPietzschmann** [comment]
Try customizing the `entry_ordinal` as described here: https://github.com/LukasPietzschmann/telescope-tabs#entry_ordinal

By default, this is set to the names of all opened files in a tab. If you change this to the tabs cwd it should work as you expect it.

**Comment by Drllap** [comment]
Thanks, worked like a charm

**Comment by LukasPietzschmann** [comment]
Great!
I think I should document it better, that the `entry_ordinal` is also used by the fuzzy search engine. I'll do this as soon as I've got time.

By the way, I think it's sooo cool that somebody (you) actually uses my stuff. So thanks a lot for trying it out and giving me some feedback!
