### ISSUE TITLE
go_to_previous throws if the previews tab has been deleted

### ISSUE THREAD

**Issue by Drllap** [LukasPietzschmann/telescope-tabs#6]
### Error:
![image](https://user-images.githubusercontent.com/3659986/208089717-0811c36f-3cba-4af4-8957-71f947548f30.png)

### Steps to reproduce:
* `:tabnew`
* Use `list_tabs` to got to some tab
* `:tabclose`
* call `go_to_privious
* Error

**Comment by LukasPietzschmann** [comment]
Thanks a lot for reporting!
Actually, you don't even have to use `:tabnew`. You can just close the current tab to trigger this behavior.
