### ISSUE TITLE
go_to_previous should account for built in tab movements

### ISSUE THREAD

**Issue by Drllap** [LukasPietzschmann/telescope-tabs#7]
`go_to_previous` should update the "previous" when things like `gt`, `gT`, `:tabnext` are used

**Comment by LukasPietzschmann** [comment]
Maybe I'm misunderstanding the issue, but when I use `gt`, `gT`, or `:tabnext` to switch between tabs, `go_to_previous` still works fine and switches to the last used tab.

**Comment by Drllap** [comment]
You are right, looks like it is. Not sure what going on earlier for me. Closing, will just reopen if I run into something weird again
