### ISSUE TITLE
Telescope extension list

### ISSUE THREAD

**Issue by TC72** [LukasPietzschmann/telescope-tabs#9]
Just a message to let you know I moved your extension to the right place on the telescope wiki.
The instructions say "Please append your extensions at the bottom, not at the top."

![CleanShot 2023-01-13 at 16 29 54](https://user-images.githubusercontent.com/402357/212370652-3029be5a-1aa2-4196-861a-82ca28eb995f.png)

**Comment by LukasPietzschmann** [comment]
I probably missed the line stating this. So thanks a lot for correcting my mistake ':)
